### ISSUE TITLE
run to fixed certainty

### ISSUE THREAD

**Issue by jkroso** [vesln/b#4]
I think fixed iteration and fixed time benchmarks will both be affected by hard to predict platform level performance fluctuations. e.g. if you run the same file in a comparison against itself the second instance will be faster 9 times in 10. I guess the hardware warms up or something. A way around this would be to take multiple samples until the sample error falls below a certain level. __statistics theory__ required though!

**Comment by davedoesdev** [comment]
Hey @jkroso did you decide not to do this?

**Comment by jkroso** [comment]
Not as such but it's not likely I'll do it  anytime soon

**Comment by davedoesdev** [comment]
:( No time to do it either. This could have been the best Node benchmark module.
Anyway, all the best.
